spring:
  rabbitmq:
    host: 192.168.1.7
    port: 5672
    virtual-host: zexi
    username: zexi
    password: zexi
    publisher-confirm-type: correlated
    publisher-returns: true # 开启生产者返回
    listener:
      simple:
        acknowledge-mode: manual # 开启手动确认
